### ISSUE TITLE
Registration Support (via MATLAB executable)

### ISSUE THREAD

**Issue by jakirkham** [jakirkham/ilastik#25]
Provide support for registration with Simon's pipeline. Ideally, Python bindings will not be required and it can be used by command line. Alternatively, bindings should be provided.

**Comment by jakirkham** [comment]
No longer using Simon's pipeline. Now will be using code from Wenzhi, which will be added into the pipeline.

**Comment by fdiego** [comment]
I'll keep open this issue just in case we want to integrate Simon's pipeline
